// test data for analytics page


export const dataSource = [
  {
    key: '1',
    Company_Name: 'Apple',
    Email: 'tttttttttttttttttttttttest@gmail.com',
    LastLog: '10-12-24-05:33 PM',
    Enriched_Leads: '423',
    Emails_Sent: '5435',
    Active_Campaings: '543543',
    Campaings_Created: '3',
    Active_L_Campaings: '3',
    Email_Accounts: '3',
    LinkedIn_Accounts: '3',
    Connections_Sent: '3',
    Total_Sessions: '3',
  },
  {
    key: '2',
    Company_Name: 'Apple',
    Email: 'test@gmail.com',
    LastLog: '11-10-24-11:25 AM',
    Enriched_Leads: '678',
    Emails_Sent: '9876',
    Active_Campaings: '123456',
    Campaings_Created: '5',
    Active_L_Campaings: '2',
    Email_Accounts: '4',
    LinkedIn_Accounts: '2',
    Connections_Sent: '6',
    Total_Sessions: '8',
  },
  {
    key: '3',
    Company_Name: 'Devon Inc',
    Email: 'devon@example.com',
    LastLog: '10-11-24-01:00 PM',
    Enriched_Leads: '359',
    Emails_Sent: '7531',
    Active_Campaings: '234567',
    Campaings_Created: '7',
    Active_L_Campaings: '4',
    Email_Accounts: '2',
    LinkedIn_Accounts: '3',
    Connections_Sent: '8',
    Total_Sessions: '5',
  },
  {
    key: '4',
    Company_Name: 'Google',
    Email: 'google@example.com',
    LastLog: '09-25-24-03:45 PM',
    Enriched_Leads: '512',
    Emails_Sent: '6547',
    Active_Campaings: '765432',
    Campaings_Created: '6',
    Active_L_Campaings: '5',
    Email_Accounts: '6',
    LinkedIn_Accounts: '4',
    Connections_Sent: '9',
    Total_Sessions: '7',
  },
  {
    key: '5',
    Company_Name: 'Rest',
    Email: 'rest@example.com',
    LastLog: '08-12-24-04:30 PM',
    Enriched_Leads: '789',
    Emails_Sent: '8123',
    Active_Campaings: '543210',
    Campaings_Created: '9',
    Active_L_Campaings: '3',
    Email_Accounts: '5',
    LinkedIn_Accounts: '3',
    Connections_Sent: '7',
    Total_Sessions: '6',
  },
  {
    key: '6',
    Company_Name: 'Google',
    Email: 'test@gmail.com',
    LastLog: '07-15-24-06:10 AM',
    Enriched_Leads: '234',
    Emails_Sent: '6789',
    Active_Campaings: '123456',
    Campaings_Created: '4',
    Active_L_Campaings: '2',
    Email_Accounts: '3',
    LinkedIn_Accounts: '2',
    Connections_Sent: '5',
    Total_Sessions: '4',
  },
  {
    key: '7',
    Company_Name: 'Microsoft',
    Email: 'microsoft@example.com',
    LastLog: '06-20-24-02:15 PM',
    Enriched_Leads: '456',
    Emails_Sent: '3456',
    Active_Campaings: '987654',
    Campaings_Created: '8',
    Active_L_Campaings: '3',
    Email_Accounts: '4',
    LinkedIn_Accounts: '1',
    Connections_Sent: '7',
    Total_Sessions: '5',
  },
  {
    key: '8',
    Company_Name: 'Google',
    Email: 'example@google.com',
    LastLog: '05-05-24-10:00 AM',
    Enriched_Leads: '678',
    Emails_Sent: '1234',
    Active_Campaings: '876543',
    Campaings_Created: '7',
    Active_L_Campaings: '4',
    Email_Accounts: '2',
    LinkedIn_Accounts: '3',
    Connections_Sent: '8',
    Total_Sessions: '6',
  },
  {
    key: '9',
    Company_Name: 'XXeron',
    Email: 'xxeron@example.com',
    LastLog: '04-14-24-07:20 PM',
    Enriched_Leads: '789',
    Emails_Sent: '3456',
    Active_Campaings: '543210',
    Campaings_Created: '9',
    Active_L_Campaings: '5',
    Email_Accounts: '4',
    LinkedIn_Accounts: '2',
    Connections_Sent: '9',
    Total_Sessions: '7',
  },
  {
    key: '10',
    Company_Name: 'Google',
    Email: 'google2@example.com',
    LastLog: '03-22-24-05:33 PM',
    Enriched_Leads: '321',
    Emails_Sent: '5435',
    Active_Campaings: '543543',
    Campaings_Created: '3',
    Active_L_Campaings: '3',
    Email_Accounts: '3',
    LinkedIn_Accounts: '3',
    Connections_Sent: '3',
    Total_Sessions: '3',
  },
  {
    key: '11',
    Company_Name: 'JerryOne Inc',
    Email: 'jerryone@example.com',
    LastLog: '02-17-24-08:33 PM',
    Enriched_Leads: '512',
    Emails_Sent: '8765',
    Active_Campaings: '654321',
    Campaings_Created: '5',
    Active_L_Campaings: '2',
    Email_Accounts: '4',
    LinkedIn_Accounts: '1',
    Connections_Sent: '6',
    Total_Sessions: '4',
  },
  {
    key: '12',
    Company_Name: 'JerryOne Inc',
    Email: 'jerryone2@example.com',
    LastLog: '01-12-24-10:00 AM',
    Enriched_Leads: '789',
    Emails_Sent: '4321',
    Active_Campaings: '765432',
    Campaings_Created: '7',
    Active_L_Campaings: '3',
    Email_Accounts: '5',
    LinkedIn_Accounts: '2',
    Connections_Sent: '7',
    Total_Sessions: '5',
  },
  {
    key: '13',
    Company_Name: 'Brex',
    Email: 'brex@example.com',
    LastLog: '12-05-23-09:15 PM',
    Enriched_Leads: '678',
    Emails_Sent: '5432',
    Active_Campaings: '876543',
    Campaings_Created: '6',
    Active_L_Campaings: '4',
    Email_Accounts: '3',
    LinkedIn_Accounts: '1',
    Connections_Sent: '8',
    Total_Sessions: '6',
  },
  {
    key: '14',
    Company_Name: 'Apple',
    Email: 'apple2@example.com',
    LastLog: '11-22-23-11:30 AM',
    Enriched_Leads: '321',
    Emails_Sent: '6543',
    Active_Campaings: '543210',
    Campaings_Created: '5',
    Active_L_Campaings: '2',
    Email_Accounts: '4',
    LinkedIn_Accounts: '3',
    Connections_Sent: '6',
    Total_Sessions: '4',
  },
  {
    key: '15',
    Company_Name: 'Microsoft',
    Email: 'example1@microsoft.com',
    LastLog: '11-05-23-02:15 PM',
    Enriched_Leads: '512',
    Emails_Sent: '3421',
    Active_Campaings: '231231',
    Campaings_Created: '7',
    Active_L_Campaings: '2',
    Email_Accounts: '5',
    LinkedIn_Accounts: '1',
    Connections_Sent: '10',
    Total_Sessions: '6',
  },
  {
    key: '16',
    Company_Name: 'Google',
    Email: 'example2@google.com',
    LastLog: '09-30-22-10:45 AM',
    Enriched_Leads: '678',
    Emails_Sent: '8993',
    Active_Campaings: '999999',
    Campaings_Created: '9',
    Active_L_Campaings: '5',
    Email_Accounts: '6',
    LinkedIn_Accounts: '2',
    Connections_Sent: '15',
    Total_Sessions: '8',
  },
  {
    key: '17',
    Company_Name: 'Amazon',
    Email: 'example3@amazon.com',
    LastLog: '12-18-24-08:00 AM',
    Enriched_Leads: '243',
    Emails_Sent: '4322',
    Active_Campaings: '543123',
    Campaings_Created: '12',
    Active_L_Campaings: '8',
    Email_Accounts: '4',
    LinkedIn_Accounts: '3',
    Connections_Sent: '20',
    Total_Sessions: '12',
  },
  {
    key: '18',
    Company_Name: 'Facebook',
    Email: 'example4@facebook.com',
    LastLog: '01-22-23-01:25 PM',
    Enriched_Leads: '789',
    Emails_Sent: '5123',
    Active_Campaings: '876543',
    Campaings_Created: '5',
    Active_L_Campaings: '3',
    Email_Accounts: '7',
    LinkedIn_Accounts: '5',
    Connections_Sent: '25',
    Total_Sessions: '15',
  },
  {
    key: '19',
    Company_Name: 'Netflix',
    Email: 'example5@netflix.com',
    LastLog: '05-14-22-11:10 AM',
    Enriched_Leads: '352',
    Emails_Sent: '4211',
    Active_Campaings: '543678',
    Campaings_Created: '6',
    Active_L_Campaings: '4',
    Email_Accounts: '2',
    LinkedIn_Accounts: '4',
    Connections_Sent: '18',
    Total_Sessions: '10',
  }
];

export const columns = [
  {
    title: 'Company Name',
    dataIndex: 'Company_Name',
    key: 'Compay_name',
    sorter: (a, b) => a.Company_Name.localeCompare(b.Company_Name),
    //defaultSortOrder: 'descend', //Default to most recent at top
    width: 200, // Set the width for the Email column
  },
  {
    title: 'User Email',
    dataIndex: 'Email',
    key: 'Email',
    width: 200, // Set the width for the Email column
  },
  {
    title: 'Last Logged In',
    dataIndex: 'LastLog',
    key: 'LastLog',
    width: 200, // Set the width for the Email column
    sorter: (a, b) => new Date(a.LastLog) - new Date(b.LastLog), // Add sorter for LastLog

  },
  {
    title: 'Enriched Leads',
    dataIndex: 'Enriched_Leads',
    key: 'Enriched_Leads',
    width: 200, // Set the width for the Email column
  },
  {
    title: 'Emails Sent',
    dataIndex: 'Emails_Sent',
    key: 'Emails_Sent',
    sorter: (a, b) => a.Emails_Sent - b.Emails_Sent,
    width: 200, // Set the width for the Email column
  },
  {
    title: 'Active Campaings',
    dataIndex: 'Active_Campaings',
    key: 'Active_Campaings',
    width: 200, // Set the width for the Email column
  },
  {
    title: 'Campaings Created',
    dataIndex: 'Campaings_Created',
    key: 'Campaings_Created',
    width: 200, // Set the width for the Email column
  },
  {
    title: 'Active L Campaings',
    dataIndex: 'Active_L_Campaings',
    key: 'Active_L_Campaings',
    sorter: (a, b) => a.Campaigns_Created - b.Campaigns_Created,
    width: 200, // Set the width for the Email column
  },
  {
    title: 'Email Accounts',
    dataIndex: 'Email_Accounts',
    key: 'Email_Accounts',
    sorter: (a, b) => a.Email_Accounts - b.Email_Accounts,
    width: 200, // Set the width for the Email column
  },
  {
    title: 'LinkedIn Accounts',
    dataIndex: 'LinkedIn_Accounts',
    key: 'LinkedIn_Accounts',
    sorter: (a, b) => a.LinkedIn_Accounts - b.LinkedIn_Accounts,
    width: 200, // Set the width for the Email column
  },
  {
    title: 'Connections Sent',
    dataIndex: 'Connections_Sent',
    key: 'Connections_Sent',
    sorter: (a, b) => a.Connections_Sent - b.Connections_Sent,
    width: 200, // Set the width for the Email column
  },
  {
    title: 'Total Sessions',
    dataIndex: 'Total_Sessions',
    key: 'Total_Sessions',
    sorter: (a, b) => a.Total_Sessions - b.Total_Sessions,
    width: 200, // Set the width for the Email column
  },
];

