// test data for analytics page


export const dataSource = [
  {
    key: '1',
    company_name: 'Apple',
    user_email: 'tttttttttttttttttttttttest@gmail.com',
    last_login: '10-12-24-05:33 PM',
    enriched_leads: '423',
    email_sent: '5435',
    active_campaigns: '543543',
    campaigns_created: '3',
    active_linkedin_campaigns: '3',
    email_accounts: '3',
    linkedin_accounts: '3',
    connections_sent: '3',
    total_sessions: '3',
  },
  {
    key: '2',
    company_name: 'Apple',
    user_email: 'test@gmail.com',
    last_login: '11-10-24-11:25 AM',
    enriched_leads: '678',
    email_sent: '9876',
    active_campaigns: '123456',
    campaigns_created: '5',
    active_linkedin_campaigns: '2',
    email_accounts: '4',
    linkedin_accounts: '2',
    connections_sent: '6',
    total_sessions: '8',
  },
  {
    key: '3',
    company_name: 'Devon Inc',
    user_email: 'devon@example.com',
    last_login: '10-11-24-01:00 PM',
    enriched_leads: '359',
    email_sent: '7531',
    active_campaigns: '234567',
    campaigns_created: '7',
    active_linkedin_campaigns: '4',
    email_accounts: '2',
    linkedin_accounts: '3',
    connections_sent: '8',
    total_sessions: '5',
  },
  {
    key: '4',
    company_name: 'Google',
    user_email: 'google@example.com',
    last_login: '09-25-24-03:45 PM',
    enriched_leads: '512',
    email_sent: '6547',
    active_campaigns: '765432',
    campaigns_created: '6',
    active_linkedin_campaigns: '5',
    email_accounts: '6',
    linkedin_accounts: '4',
    connections_sent: '9',
    total_sessions: '7',
  },
  {
    key: '5',
    company_name: 'Rest',
    user_email: 'rest@example.com',
    last_login: '08-12-24-04:30 PM',
    enriched_leads: '789',
    email_sent: '8123',
    active_campaigns: '543210',
    campaigns_created: '9',
    active_linkedin_campaigns: '3',
    email_accounts: '5',
    linkedin_accounts: '3',
    connections_sent: '7',
    total_sessions: '6',
  },
  {
    key: '6',
    company_name: 'Google',
    user_email: 'test@gmail.com',
    last_login: '07-15-24-06:10 AM',
    enriched_leads: '234',
    email_sent: '6789',
    active_campaigns: '123456',
    campaigns_created: '4',
    active_linkedin_campaigns: '2',
    email_accounts: '3',
    linkedin_accounts: '2',
    connections_sent: '5',
    total_sessions: '4',
  },
  {
    key: '7',
    company_name: 'Microsoft',
    user_email: 'microsoft@example.com',
    last_login: '06-20-24-02:15 PM',
    enriched_leads: '456',
    email_sent: '3456',
    active_campaigns: '987654',
    campaigns_created: '8',
    active_linkedin_campaigns: '3',
    email_accounts: '4',
    linkedin_accounts: '1',
    connections_sent: '7',
    total_sessions: '5',
  },
  {
    key: '8',
    company_name: 'Google',
    user_email: 'example@google.com',
    last_login: '05-05-24-10:00 AM',
    enriched_leads: '678',
    email_sent: '1234',
    active_campaigns: '876543',
    campaigns_created: '7',
    active_linkedin_campaigns: '4',
    email_accounts: '2',
    linkedin_accounts: '3',
    connections_sent: '8',
    total_sessions: '6',
  },
  {
    key: '9',
    company_name: 'XXeron',
    user_email: 'xxeron@example.com',
    last_login: '04-14-24-07:20 PM',
    enriched_leads: '789',
    email_sent: '3456',
    active_campaigns: '543210',
    campaigns_created: '9',
    active_linkedin_campaigns: '5',
    email_accounts: '4',
    linkedin_accounts: '2',
    connections_sent: '9',
    total_sessions: '7',
  },
  {
    key: '10',
    company_name: 'Google',
    user_email: 'google2@example.com',
    last_login: '03-22-24-05:33 PM',
    enriched_leads: '321',
    email_sent: '5435',
    active_campaigns: '543543',
    campaigns_created: '3',
    active_linkedin_campaigns: '3',
    email_accounts: '3',
    linkedin_accounts: '3',
    connections_sent: '3',
    total_sessions: '3',
  },
  {
    key: '11',
    company_name: 'JerryOne Inc',
    user_email: 'jerryone@example.com',
    last_login: '02-17-24-08:33 PM',
    enriched_leads: '512',
    email_sent: '8765',
    active_campaigns: '654321',
    campaigns_created: '5',
    active_linkedin_campaigns: '2',
    email_accounts: '4',
    linkedin_accounts: '1',
    connections_sent: '6',
    total_sessions: '4',
  },
  {
    key: '12',
    company_name: 'JerryOne Inc',
    user_email: 'jerryone2@example.com',
    last_login: '01-12-24-10:00 AM',
    enriched_leads: '789',
    email_sent: '4321',
    active_campaigns: '765432',
    campaigns_created: '7',
    active_linkedin_campaigns: '3',
    email_accounts: '5',
    linkedin_accounts: '2',
    connections_sent: '7',
    total_sessions: '5',
  },
  {
    key: '13',
    company_name: 'Brex',
    user_email: 'brex@example.com',
    last_login: '12-05-23-09:15 PM',
    enriched_leads: '678',
    email_sent: '5432',
    active_campaigns: '876543',
    campaigns_created: '6',
    active_linkedin_campaigns: '4',
    email_accounts: '3',
    linkedin_accounts: '1',
    connections_sent: '8',
    total_sessions: '6',
  },
  {
    key: '14',
    company_name: 'Apple',
    user_email: 'apple2@example.com',
    last_login: '11-22-23-11:30 AM',
    enriched_leads: '321',
    email_sent: '6543',
    active_campaigns: '543210',
    campaigns_created: '5',
    active_linkedin_campaigns: '2',
    email_accounts: '4',
    linkedin_accounts: '3',
    connections_sent: '6',
    total_sessions: '4',
  },
  {
    key: '15',
    company_name: 'Microsoft',
    user_email: 'example1@microsoft.com',
    last_login: '11-05-23-02:15 PM',
    enriched_leads: '512',
    email_sent: '3421',
    active_campaigns: '231231',
    campaigns_created: '7',
    active_linkedin_campaigns: '2',
    email_accounts: '5',
    linkedin_accounts: '1',
    connections_sent: '10',
    total_sessions: '6',
  },
  {
    key: '16',
    company_name: 'Google',
    user_email: 'example2@google.com',
    last_login: '09-30-22-10:45 AM',
    enriched_leads: '678',
    email_sent: '8993',
    active_campaigns: '999999',
    campaigns_created: '9',
    active_linkedin_campaigns: '5',
    email_accounts: '6',
    linkedin_accounts: '2',
    connections_sent: '15',
    total_sessions: '8',
  },
  {
    key: '17',
    company_name: 'Amazon',
    user_email: 'example3@amazon.com',
    last_login: '12-18-24-08:00 AM',
    enriched_leads: '243',
    email_sent: '4322',
    active_campaigns: '543123',
    campaigns_created: '12',
    active_linkedin_campaigns: '8',
    email_accounts: '4',
    linkedin_accounts: '3',
    connections_sent: '20',
    total_sessions: '12',
  },
  {
    key: '18',
    company_name: 'Facebook',
    user_email: 'example4@facebook.com',
    last_login: '01-22-23-01:25 PM',
    enriched_leads: '789',
    email_sent: '5123',
    active_campaigns: '876543',
    campaigns_created: '5',
    active_linkedin_campaigns: '3',
    email_accounts: '7',
    linkedin_accounts: '5',
    connections_sent: '25',
    total_sessions: '15',
  },
  {
    key: '19',
    company_name: 'Netflix',
    user_email: 'example5@netflix.com',
    last_login: '05-14-22-11:10 AM',
    enriched_leads: '352',
    email_sent: '4211',
    active_campaigns: '543678',
    campaigns_created: '6',
    active_linkedin_campaigns: '4',
    email_accounts: '2',
    linkedin_accounts: '4',
    connections_sent: '18',
    total_sessions: '10',
  }
];

export const columns = [
  {
    title: 'Company Name',
    dataIndex: 'company_name',
    key: 'company_name',
    sorter: (a, b) => a.company_name.localeCompare(b.company_name),
    //defaultSortOrder: 'descend', //Default to most recent at top
    width: 200, // Set the width for the user_email column
  },
  {
    title: 'User user_email',
    dataIndex: 'user_email',
    key: 'user_email',
    width: 200, // Set the width for the user_email column
  },
  {
    title: 'Last Logged In',
    dataIndex: 'last_login',
    key: 'last_login',
    width: 200, // Set the width for the user_email column
    sorter: (a, b) => new Date(a.last_login) - new Date(b.last_login), // Add sorter for last_login

  },
  {
    title: 'Enriched Leads',
    dataIndex: 'enriched_leads',
    key: 'enriched_leads',
    width: 200, // Set the width for the user_email column
  },
  {
    title: 'user_emails Sent',
    dataIndex: 'email_sent',
    key: 'email_sent',
    sorter: (a, b) => a.email_sent - b.email_sent,
    width: 200, // Set the width for the user_email column
  },
  {
    title: 'Active Campaings',
    dataIndex: 'active_campaigns',
    key: 'active_campaigns',
    width: 200, // Set the width for the user_email column
  },
  {
    title: 'Campaings Created',
    dataIndex: 'campaigns_created',
    key: 'campaigns_created',
    width: 200, // Set the width for the user_email column
  },
  {
    title: 'Active L Campaings',
    dataIndex: 'active_linkedin_campaigns',
    key: 'active_linkedin_campaigns',
    sorter: (a, b) => a.active_linkedin_campaigns- b.active_linkedin_campaigns,
    width: 200, // Set the width for the user_email column
  },
  {
    title: 'user_email Accounts',
    dataIndex: 'email_accounts',
    key: 'email_accounts',
    sorter: (a, b) => a.email_accounts - b.email_accounts,
    width: 200, // Set the width for the user_email column
  },
  {
    title: 'LinkedIn Accounts',
    dataIndex: 'linkedin_accounts',
    key: 'linkedin_accounts',
    sorter: (a, b) => a.linkedin_accounts - b.linkedin_accounts,
    width: 200,
  },
  {
    title: 'Connections Sent',
    dataIndex: 'connections_sent',
    key: 'connections_sent',
    sorter: (a, b) => a.connections_sent - b.connections_sent,
    width: 200,
  },
  {
    title: 'Total Sessions',
    dataIndex: 'total_sessions',
    key: 'total_sessions',
    sorter: (a, b) => a.total_sessions - b.total_sessions,
    width: 200, 
  },
];

